apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  replicas: 1
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.6.4
        ports:
        - name: mongodb
          containerPort: 27017
        volumeMounts:
        - name: mongo-pvc
          mountPath: /data/db
        command: ["docker-entrypoint.sh", "--replSet", "rs"]
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc
    spec:
      storageClassName: mongo-sc
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
