apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
spec:
  storageClassName: mongo-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  local:
    path: /data/pv-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
